package postgres

import (
	"strings"
	"testing"

	"smt/internal/driver"
)

func TestDeterministicCreateTableMSSQLToPostgres(t *testing.T) {
	renderer := newDeterministicDDL()
	table := &driver.Table{
		Schema:     "dbo",
		Name:       "PostLinks",
		PrimaryKey: []string{"Id"},
		Columns: []driver.Column{
			{Name: "Id", DataType: "int", Precision: 10, IsIdentity: true, IsNullable: false},
			{Name: "CreationDate", DataType: "datetime", IsNullable: false},
			{Name: "RelatedPostId", DataType: "int", Precision: 10, IsNullable: false},
			{Name: "LinkTypeId", DataType: "int", Precision: 10, IsNullable: false},
		},
	}

	ddl, columnTypes, err := renderer.createTable(table, "public", false)
	if err != nil {
		t.Fatalf("createTable: %v", err)
	}

	assertContains(t, ddl, `CREATE TABLE "public"."postlinks"`)
	assertContains(t, ddl, `"id" integer GENERATED BY DEFAULT AS IDENTITY`)
	assertContains(t, ddl, `"creationdate" timestamp without time zone NOT NULL`)
	assertContains(t, ddl, `CONSTRAINT "pk_postlinks" PRIMARY KEY ("id")`)
	if got := columnTypes["Id"]; got != "integer GENERATED BY DEFAULT AS IDENTITY" {
		t.Fatalf("columnTypes[Id] = %q", got)
	}
}

func TestDeterministicCreateTableStringLengths(t *testing.T) {
	renderer := newDeterministicDDL()
	table := &driver.Table{
		Name: "Users",
		Columns: []driver.Column{
			{Name: "DisplayName", DataType: "nvarchar", MaxLength: 40, IsNullable: false},
			{Name: "AboutMe", DataType: "nvarchar", MaxLength: -1, IsNullable: true},
			{Name: "WebsiteUrl", DataType: "varchar", MaxLength: 200, IsNullable: true},
		},
	}

	ddl, _, err := renderer.createTable(table, "public", false)
	if err != nil {
		t.Fatalf("createTable: %v", err)
	}

	assertContains(t, ddl, `"displayname" character varying(40) NOT NULL`)
	assertContains(t, ddl, `"aboutme" text`)
	assertContains(t, ddl, `"websiteurl" character varying(200)`)
}

func TestDeterministicFinalizationDDL(t *testing.T) {
	renderer := newDeterministicDDL()
	table := &driver.Table{Name: "Votes"}

	idxDDL, err := renderer.createIndex(table, &driver.Index{
		Name:     "IX_Votes_PostId",
		Columns:  []string{"PostId"},
		IsUnique: false,
	}, "public")
	if err != nil {
		t.Fatalf("createIndex: %v", err)
	}
	assertContains(t, idxDDL, `CREATE INDEX "ix_votes_postid" ON "public"."votes" ("postid")`)

	fkDDL, err := renderer.createForeignKey(table, &driver.ForeignKey{
		Name:       "FK_Votes_Posts",
		Columns:    []string{"PostId"},
		RefTable:   "Posts",
		RefColumns: []string{"Id"},
		OnDelete:   "NO ACTION",
	}, "public")
	if err != nil {
		t.Fatalf("createForeignKey: %v", err)
	}
	assertContains(t, fkDDL, `ALTER TABLE "public"."votes" ADD CONSTRAINT "fk_votes_posts" FOREIGN KEY ("postid") REFERENCES "public"."posts" ("id")`)

	checkDDL, err := renderer.createCheckConstraint(table, &driver.CheckConstraint{
		Name:       "CK_Votes_BountyAmount",
		Definition: "([BountyAmount]>(0))",
	}, "public")
	if err != nil {
		t.Fatalf("createCheckConstraint: %v", err)
	}
	assertContains(t, checkDDL, `ALTER TABLE "public"."votes" ADD CONSTRAINT "ck_votes_bountyamount" CHECK ("bountyamount">(0))`)
}

func TestDeterministicUnsupportedTypeFails(t *testing.T) {
	renderer := newDeterministicDDL()
	_, err := renderer.columnType(driver.Column{Name: "Mystery", DataType: "sql_variant"})
	if err == nil {
		t.Fatal("expected unsupported type error")
	}
}

func TestDeterministicUnsafeDefaultExpressionFails(t *testing.T) {
	renderer := newDeterministicDDL()
	_, _, err := renderer.columnDefinition(driver.Column{
		Name:              "ExpiresAt",
		DataType:          "datetime",
		IsNullable:        false,
		DefaultExpression: "(DATEADD(day, 1, GETDATE()))",
	})
	if err == nil {
		t.Fatal("expected unsupported default expression error")
	}
}

func TestDeterministicUnsafeCheckExpressionFails(t *testing.T) {
	renderer := newDeterministicDDL()
	_, err := renderer.createCheckConstraint(&driver.Table{Name: "Users"}, &driver.CheckConstraint{
		Name:       "CK_Users_Email",
		Definition: "(CHARINDEX('@', [Email]) > 0)",
	}, "public")
	if err == nil {
		t.Fatal("expected unsupported check expression error")
	}
}

func assertContains(t *testing.T, s, substr string) {
	t.Helper()
	if !strings.Contains(s, substr) {
		t.Fatalf("expected:\n%s\nto contain:\n%s", s, substr)
	}
}
