package postgres

import (
	"fmt"
	"net/url"
	"strings"
)

// Dialect implements driver.Dialect for PostgreSQL.
type Dialect struct{}

func (d *Dialect) DBType() string { return "postgres" }

func (d *Dialect) QuoteIdentifier(name string) string {
	return `"` + strings.ReplaceAll(name, `"`, `""`) + `"`
}

func (d *Dialect) QualifyTable(schema, table string) string {
	return d.QuoteIdentifier(schema) + "." + d.QuoteIdentifier(table)
}

func (d *Dialect) BuildDSN(host string, port int, database, user, password string, opts map[string]any) string {
	encodedUser := url.QueryEscape(user)
	encodedPassword := url.QueryEscape(password)
	encodedDatabase := url.QueryEscape(database)

	dsn := fmt.Sprintf("postgres://%s:%s@%s:%d/%s",
		encodedUser, encodedPassword, host, port, encodedDatabase)

	params := url.Values{}
	if sslMode, ok := opts["sslmode"].(string); ok && sslMode != "" {
		params.Set("sslmode", sslMode)
	} else {
		params.Set("sslmode", "prefer")
	}

	if len(params) > 0 {
		dsn += "?" + params.Encode()
	}
	return dsn
}

func (d *Dialect) ParameterPlaceholder(index int) string {
	return fmt.Sprintf("$%d", index)
}

func (d *Dialect) RowCountQuery(useStats bool) string {
	if useStats {
		return `SELECT COALESCE(n_live_tup, 0) FROM pg_stat_user_tables WHERE schemaname = $1 AND relname = $2`
	}
	return `SELECT COUNT(*) FROM %s`
}

// AIPromptAugmentation returns PostgreSQL-specific instructions for AI DDL generation.
func (d *Dialect) AIPromptAugmentation() string {
	return `
CRITICAL PostgreSQL identifier rules:
- Column and table names MUST preserve the exact spelling and underscores from the source name
- The ONLY allowed transformation is lowercasing letters in identifiers
- Do NOT abbreviate, shorten, remove underscores, or change any non-letter characters
- Underscores MUST be preserved: user_id → user_id (NOT userid)
- CamelCase is only lowercased: LastEditorDisplayName → lasteditordisplayname
- Example: created_at → created_at (NOT createdat)
- Example: post_id → post_id (NOT postid)
- Do NOT use double-quotes around identifiers unless the name is a reserved word

CRITICAL PostgreSQL IDENTITY column rules:
- When source has IDENTITY/AUTO_INCREMENT columns, preserve them in target
- Use 'GENERATED ALWAYS AS IDENTITY' for columns that never allow manual values
- Use 'GENERATED BY DEFAULT AS IDENTITY' for columns that allow manual inserts during migration
- PostgreSQL auto-generates sequence names as: tablename_columnname_seq
- Example: id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY
- NEVER omit IDENTITY specification when source column has IDENTITY/AUTO_INCREMENT

CRITICAL PostgreSQL timezone-awareness rules:
- Source datetime types WITHOUT timezone — MSSQL ` + "`datetime`" + `, ` + "`datetime2`" + `, ` + "`smalldatetime`" + `;
  MySQL ` + "`datetime`" + ` — MUST map to PostgreSQL ` + "`TIMESTAMP`" + ` (alias for ` + "`timestamp without time zone`" + `).
  Do NOT use ` + "`TIMESTAMPTZ`" + ` / ` + "`timestamp with time zone`" + ` for these — that silently adds
  TZ semantics the source never had. Behavior on read flips from "naive local" to
  "session-TZ converted," which is a wire-format change.
- Source datetime types WITH timezone — MSSQL ` + "`datetimeoffset`" + `; MySQL ` + "`timestamp`" + ` (which
  stores in UTC and converts on read) — MUST map to ` + "`TIMESTAMPTZ`" + ` / ` + "`timestamp with time zone`" + `.
- Quick mapping table:
    MSSQL ` + "`datetime`" + `       -> PG ` + "`TIMESTAMP`" + `
    MSSQL ` + "`datetime2(N)`" + `   -> PG ` + "`TIMESTAMP(N)`" + `   (preserve N if reported in scale)
    MSSQL ` + "`smalldatetime`" + `  -> PG ` + "`TIMESTAMP`" + `
    MSSQL ` + "`datetimeoffset(N)`" + ` -> PG ` + "`TIMESTAMPTZ(N)`" + ` (preserve N if reported in scale)
    MySQL ` + "`datetime(N)`" + `    -> PG ` + "`TIMESTAMP(N)`" + `
    MySQL ` + "`timestamp(N)`" + `   -> PG ` + "`TIMESTAMPTZ(N)`" + `

CRITICAL PostgreSQL VARCHAR length rule:
- Translate source ` + "`varchar(N)`" + ` / ` + "`nvarchar(N)`" + ` / ` + "`character varying(N)`" + ` one-to-one to PG ` + "`VARCHAR(N)`" + `:
  ` + "`varchar(20)`" + ` -> ` + "`VARCHAR(20)`" + `, ` + "`nvarchar(200)`" + ` -> ` + "`VARCHAR(200)`" + `.
- Do NOT round, halve, double, substitute, or drop the length argument. Both N values
  count CHARACTERS — they're the same number, not a unit conversion. Shrinking is data-lossy
  on insert; growing wastes storage.
`
}

// AIDropTablePromptAugmentation returns PostgreSQL-specific instructions for DROP TABLE DDL.
func (d *Dialect) AIDropTablePromptAugmentation() string {
	return `
PostgreSQL-specific requirements:
- Use DROP TABLE IF EXISTS with CASCADE to drop dependent objects
- Quote identifiers with double quotes if they contain special characters or are reserved words
- Use lowercase table names (PostgreSQL folds unquoted identifiers to lowercase)
`
}
