package mssql

import (
	"fmt"
	"net/url"
	"strings"
)

// Dialect implements driver.Dialect for SQL Server.
type Dialect struct{}

func (d *Dialect) DBType() string { return "mssql" }

func (d *Dialect) QuoteIdentifier(name string) string {
	return "[" + strings.ReplaceAll(name, "]", "]]") + "]"
}

func (d *Dialect) QualifyTable(schema, table string) string {
	return d.QuoteIdentifier(schema) + "." + d.QuoteIdentifier(table)
}

func (d *Dialect) BuildDSN(host string, port int, database, user, password string, opts map[string]any) string {
	encodedUser := url.QueryEscape(user)
	encodedPassword := url.QueryEscape(password)
	encodedDatabase := url.QueryEscape(database)

	dsn := fmt.Sprintf("sqlserver://%s:%s@%s:%d?database=%s",
		encodedUser, encodedPassword, host, port, encodedDatabase)

	// Add optional parameters
	if encrypt, ok := opts["encrypt"].(bool); ok {
		if encrypt {
			dsn += "&encrypt=true"
		} else {
			dsn += "&encrypt=disable"
		}
	}
	if trustCert, ok := opts["trustServerCertificate"].(bool); ok && trustCert {
		dsn += "&TrustServerCertificate=true"
	}
	if packetSize, ok := opts["packetSize"].(int); ok && packetSize > 0 {
		// Note: "packet size" is the go-mssqldb parameter name; + is URL encoding for space
		dsn += fmt.Sprintf("&packet%%20size=%d", packetSize)
	}

	// Set connection timeout to prevent indefinite hangs during login/connect.
	// go-mssqldb parameter: "connection timeout" in seconds.
	if _, ok := opts["connection timeout"]; !ok {
		dsn += "&connection+timeout=30"
	}

	// Set dial timeout for TCP connection establishment.
	if _, ok := opts["dial timeout"]; !ok {
		dsn += "&dial+timeout=15"
	}

	return dsn
}

func (d *Dialect) ParameterPlaceholder(index int) string {
	return fmt.Sprintf("@p%d", index)
}

func (d *Dialect) RowCountQuery(useStats bool) string {
	if useStats {
		return `SELECT SUM(p.rows) FROM sys.partitions p INNER JOIN sys.tables t ON p.object_id = t.object_id INNER JOIN sys.schemas s ON t.schema_id = s.schema_id WHERE s.name = @schema AND t.name = @table AND p.index_id IN (0, 1)`
	}
	return `SELECT COUNT(*) FROM %s`
}

// AIPromptAugmentation returns SQL Server-specific instructions for AI DDL
// generation. Mirrors the postgres dialect's augmentation: identity column
// translation and per-character length / Unicode-vs-codepage semantics.
// The IDENTITY guidance is corrective — without it, AI models routinely
// emit plain `INT NOT NULL` for what was a PostgreSQL identity column,
// breaking auto-increment on the target. The NVARCHAR length and
// VARCHAR-vs-NVARCHAR guidance is preventive — both haiku and sonnet have
// been observed translating lengths correctly in testing, but the older
// "VARCHAR uses byte lengths" phrasing here previously left room for an
// AI to scale by the byte/char ratio and we want to lock that down.
func (d *Dialect) AIPromptAugmentation() string {
	return `
CRITICAL SQL Server IDENTITY column rules:
- When the source column is auto-incrementing — PostgreSQL ` + "`GENERATED BY DEFAULT AS IDENTITY`" + `,
  ` + "`GENERATED ALWAYS AS IDENTITY`" + `, ` + "`SERIAL`" + `, ` + "`BIGSERIAL`" + `, ` + "`SMALLSERIAL`" + `, or MySQL ` + "`AUTO_INCREMENT`" + ` —
  translate it to SQL Server ` + "`IDENTITY(1,1)`" + ` on the target column.
- Example: PostgreSQL ` + "`id integer GENERATED BY DEFAULT AS IDENTITY`" + ` -> SQL Server ` + "`id INT IDENTITY(1,1) NOT NULL`" + `.
- Example: PostgreSQL ` + "`id bigserial`" + ` -> SQL Server ` + "`id BIGINT IDENTITY(1,1) NOT NULL`" + `.
- NEVER drop the auto-increment behavior: emitting plain ` + "`INT NOT NULL`" + ` for a PK that
  was identity in the source breaks INSERT semantics on the target.
- SQL Server allows only one IDENTITY column per table. If multiple source columns qualify,
  apply IDENTITY to the primary key column.

CRITICAL SQL Server NVARCHAR length rules:
- The N in ` + "`NVARCHAR(N)`" + ` counts CHARACTERS, not bytes — same semantic as PostgreSQL ` + "`varchar(N)`" + `
  and MySQL ` + "`VARCHAR(N)`" + ` with a multi-byte character set. On-disk storage is 2 bytes per
  character but the declared length is character count.
- Translate VARCHAR(N) / CHARACTER VARYING(N) from PostgreSQL one-to-one:
  ` + "`varchar(40)`" + ` -> ` + "`NVARCHAR(40)`" + `, ` + "`varchar(150)`" + ` -> ` + "`NVARCHAR(150)`" + `, ` + "`varchar(250)`" + ` -> ` + "`NVARCHAR(250)`" + `.
- Do NOT double, halve, or otherwise scale the length. ` + "`NVARCHAR(80)`" + ` for a source
  ` + "`varchar(40)`" + ` is wrong; both N values mean the same thing — max number of characters.
- Use ` + "`NVARCHAR(MAX)`" + ` for unbounded source text (PostgreSQL ` + "`text`" + `, MySQL ` + "`TEXT`" + ` family).
- Always prefer NVARCHAR over VARCHAR when migrating from PostgreSQL or MySQL.
  SQL Server VARCHAR is non-Unicode and stores data in the column's collation
  code page (1-2 bytes per character depending on collation). Inserting Unicode
  text that has no mapping in the code page is silently lossy — characters
  become ` + "`?`" + `. NVARCHAR uses UTF-16 and round-trips Unicode safely.

CRITICAL SQL Server timezone-awareness rules:
- Source datetime types WITHOUT timezone — PG ` + "`timestamp`" + ` / ` + "`timestamp without time zone`" + `;
  MySQL ` + "`datetime`" + ` — MUST map to MSSQL ` + "`DATETIME2`" + `. Do NOT use ` + "`DATETIMEOFFSET`" + ` for
  these — that silently adds TZ semantics the source never had.
- Source datetime types WITH timezone — PG ` + "`timestamptz`" + ` / ` + "`timestamp with time zone`" + `;
  MySQL ` + "`timestamp`" + ` — MUST map to MSSQL ` + "`DATETIMEOFFSET`" + `.
- Quick mapping table:
    PG ` + "`timestamp(N)`" + `       -> MSSQL ` + "`DATETIME2(N)`" + `   (preserve N from scale)
    PG ` + "`timestamptz(N)`" + `     -> MSSQL ` + "`DATETIMEOFFSET(N)`" + `
    MySQL ` + "`datetime(N)`" + `     -> MSSQL ` + "`DATETIME2(N)`" + `
    MySQL ` + "`timestamp(N)`" + `    -> MSSQL ` + "`DATETIMEOFFSET(N)`" + `

CRITICAL SQL Server computed column nullability rule:
- Computed columns (` + "`<col> AS (<expr>) PERSISTED`" + `) are implicitly nullable in SQL
  Server — their nullability is derived from the expression. NEVER append ` + "`NULL`" + ` or
  ` + "`NOT NULL`" + ` after ` + "`PERSISTED`" + ` (or after the expression in a non-persisted form).
- Wrong: ` + "`line_total AS (qty * unit_price) PERSISTED NULL`" + `  (parser error)
- Wrong: ` + "`line_total AS (qty * unit_price) PERSISTED NOT NULL`" + `  (parser error)
- Right: ` + "`line_total AS (qty * unit_price) PERSISTED`" + `
- If the source introspection metadata reports ` + "`nullable: false`" + ` on a computed
  column, do not translate that into a nullability suffix — emit just the AS form.
`
}

// AIDropTablePromptAugmentation returns SQL Server-specific instructions for DROP TABLE DDL.
func (d *Dialect) AIDropTablePromptAugmentation() string {
	return `
SQL Server-specific requirements:
- SQL Server does not support CASCADE DROP
- Use DROP TABLE IF EXISTS with schema-qualified table name
- Quote identifiers with square brackets []
- Foreign key constraints must be dropped separately before the table can be dropped
`
}
