package mssql

import (
	"strings"
	"testing"
)

// TestAIPromptAugmentation_IdentityRules pins the IDENTITY-translation
// guidance the AI sees when generating SQL Server DDL from PostgreSQL or
// MySQL sources. Without these phrases an AI tends to emit plain
// `INT NOT NULL` for what was a PostgreSQL identity column, breaking
// auto-increment on the target.
func TestAIPromptAugmentation_IdentityRules(t *testing.T) {
	d := &Dialect{}
	aug := d.AIPromptAugmentation()

	mustContain(t, aug,
		"IDENTITY(1,1)",
		"GENERATED BY DEFAULT AS IDENTITY",
		"AUTO_INCREMENT",
		"only one IDENTITY column per table",
	)
}

// TestAIPromptAugmentation_NvarcharLengthRules pins the length-preservation
// guidance. The phrasing is defensive: in observation both haiku and sonnet
// preserve lengths correctly for short prompts, but the older NVARCHAR
// guidance ("VARCHAR uses byte lengths") could be misread as license to
// scale by the byte/char ratio. The replacement says "do not double, halve,
// or scale" explicitly so future prompt edits don't regress.
func TestAIPromptAugmentation_NvarcharLengthRules(t *testing.T) {
	d := &Dialect{}
	aug := d.AIPromptAugmentation()

	mustContain(t, aug,
		"counts CHARACTERS",
		"varchar(40)`",
		"NVARCHAR(40)`",
		"Do NOT double",
		"NVARCHAR(MAX)",
	)
}

func mustContain(t *testing.T, haystack string, needles ...string) {
	t.Helper()
	for _, n := range needles {
		if !strings.Contains(haystack, n) {
			t.Errorf("prompt augmentation missing required phrase %q", n)
		}
	}
}
