package mysql

import (
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"testing"
)

func TestBuildDSNTimeouts(t *testing.T) {
	d := &Dialect{}
	dsn := d.BuildDSN("localhost", 3306, "testdb", "root", "pass", map[string]any{})

	if !strings.Contains(dsn, "writeTimeout=5m") {
		t.Errorf("DSN missing writeTimeout: %s", dsn)
	}
	if !strings.Contains(dsn, "readTimeout=5m") {
		t.Errorf("DSN missing readTimeout: %s", dsn)
	}
}

func TestBuildDSNTimeoutOverride(t *testing.T) {
	d := &Dialect{}
	dsn := d.BuildDSN("localhost", 3306, "testdb", "root", "pass", map[string]any{
		"writeTimeout": "10m",
		"readTimeout":  "10m",
	})

	// User-provided values should not be overridden
	if strings.Contains(dsn, "writeTimeout=5m") {
		t.Errorf("DSN should not override user writeTimeout: %s", dsn)
	}
	if strings.Contains(dsn, "readTimeout=5m") {
		t.Errorf("DSN should not override user readTimeout: %s", dsn)
	}
}

// TestAIPromptAugmentation_AutoIncrementRules pins the AUTO_INCREMENT
// translation guidance the AI sees when generating MySQL DDL from
// PostgreSQL or SQL Server sources.
func TestAIPromptAugmentation_AutoIncrementRules(t *testing.T) {
	d := &Dialect{}
	aug := d.AIPromptAugmentation()

	for _, needle := range []string{
		"AUTO_INCREMENT",
		"GENERATED BY DEFAULT AS IDENTITY",
		"IDENTITY(seed,inc)",
		"only one AUTO_INCREMENT column per table",
	} {
		if !strings.Contains(aug, needle) {
			t.Errorf("prompt missing required phrase %q", needle)
		}
	}
}

// TestAIPromptAugmentation_VarcharLengthAndCharset pins the length
// preservation + utf8mb4 guidance.
func TestAIPromptAugmentation_VarcharLengthAndCharset(t *testing.T) {
	d := &Dialect{}
	aug := d.AIPromptAugmentation()

	for _, needle := range []string{
		"counts CHARACTERS",
		"varchar(40)`",
		"VARCHAR(40)`",
		"Do NOT scale the length",
		"utf8mb4",
	} {
		if !strings.Contains(aug, needle) {
			t.Errorf("prompt missing required phrase %q", needle)
		}
	}
}

// TestAIPromptAugmentation_FractionalSecondPrecision is the regression test
// for issue #19. The mssql → mysql pair on the CRM fixture used to fail at
// the first table containing `DATETIME2(N) DEFAULT GETUTCDATE()` because the
// AI emitted `DATETIME(N) DEFAULT CURRENT_TIMESTAMP` (no precision argument
// on the default), which MySQL rejects with `Error 1067 (42000): Invalid
// default value`. The rule lives in the MySQL dialect's prompt augmentation
// (not in the central writeMigrationRules) because it's mysql-specific.
func TestAIPromptAugmentation_FractionalSecondPrecision(t *testing.T) {
	d := &Dialect{}
	aug := d.AIPromptAugmentation()

	for _, needle := range []string{
		"fractional-second precision",
		"scale > 0`",
		"DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)",
		"error 1067",
		"function defaults; literal-value defaults are unaffected",
	} {
		if !strings.Contains(aug, needle) {
			t.Errorf("prompt missing required phrase %q", needle)
		}
	}
}

// TestReaderDatabaseContext_Populated is the mysql side of the issue #13
// regression guard. Mirrors the postgres test.
func TestReaderDatabaseContext_Populated(t *testing.T) {
	body := readReaderSource(t)
	for _, needle := range []string{
		"func (r *Reader) DatabaseContext()",
		"dbContextOnce.Do",
		"gatherDatabaseContext(",
	} {
		if !strings.Contains(body, needle) {
			t.Errorf("reader.go missing required marker %q", needle)
		}
	}
}

// readReaderSource returns the contents of reader.go as a string. Uses
// runtime.Caller to locate the file by absolute path so the test doesn't
// depend on the working directory.
func readReaderSource(t *testing.T) string {
	t.Helper()
	_, thisFile, _, ok := runtime.Caller(0)
	if !ok {
		t.Fatal("runtime.Caller(0) failed; cannot locate reader.go")
	}
	src, err := os.ReadFile(filepath.Join(filepath.Dir(thisFile), "reader.go"))
	if err != nil {
		t.Fatalf("read reader.go: %v", err)
	}
	return string(src)
}
