package mysql

import (
	"strings"
	"testing"
)

func TestBuildDSNTimeouts(t *testing.T) {
	d := &Dialect{}
	dsn := d.BuildDSN("localhost", 3306, "testdb", "root", "pass", map[string]any{})

	if !strings.Contains(dsn, "writeTimeout=5m") {
		t.Errorf("DSN missing writeTimeout: %s", dsn)
	}
	if !strings.Contains(dsn, "readTimeout=5m") {
		t.Errorf("DSN missing readTimeout: %s", dsn)
	}
}

func TestBuildDSNTimeoutOverride(t *testing.T) {
	d := &Dialect{}
	dsn := d.BuildDSN("localhost", 3306, "testdb", "root", "pass", map[string]any{
		"writeTimeout": "10m",
		"readTimeout":  "10m",
	})

	// User-provided values should not be overridden
	if strings.Contains(dsn, "writeTimeout=5m") {
		t.Errorf("DSN should not override user writeTimeout: %s", dsn)
	}
	if strings.Contains(dsn, "readTimeout=5m") {
		t.Errorf("DSN should not override user readTimeout: %s", dsn)
	}
}

// TestAIPromptAugmentation_AutoIncrementRules pins the AUTO_INCREMENT
// translation guidance the AI sees when generating MySQL DDL from
// PostgreSQL or SQL Server sources.
func TestAIPromptAugmentation_AutoIncrementRules(t *testing.T) {
	d := &Dialect{}
	aug := d.AIPromptAugmentation()

	for _, needle := range []string{
		"AUTO_INCREMENT",
		"GENERATED BY DEFAULT AS IDENTITY",
		"IDENTITY(seed,inc)",
		"only one AUTO_INCREMENT column per table",
	} {
		if !strings.Contains(aug, needle) {
			t.Errorf("prompt missing required phrase %q", needle)
		}
	}
}

// TestAIPromptAugmentation_VarcharLengthAndCharset pins the length
// preservation + utf8mb4 guidance.
func TestAIPromptAugmentation_VarcharLengthAndCharset(t *testing.T) {
	d := &Dialect{}
	aug := d.AIPromptAugmentation()

	for _, needle := range []string{
		"counts CHARACTERS",
		"varchar(40)`",
		"VARCHAR(40)`",
		"Do NOT scale the length",
		"utf8mb4",
	} {
		if !strings.Contains(aug, needle) {
			t.Errorf("prompt missing required phrase %q", needle)
		}
	}
}
