package driver

import (
	"context"
	"strings"
	"testing"
)

// TestVerifyTableDDL_OK is the happy path under the parse+compare flow
// (#55): AI parser returns Column[] JSON whose attributes match the source,
// CompareColumns returns zero deltas, verdict.OK=true. No more "auditor says
// OK" — the comparison is mechanical.
func TestVerifyTableDDL_OK(t *testing.T) {
	parserResp := `{"columns":[
		{"name":"id","data_type":"integer","is_nullable":false,"is_identity":true},
		{"name":"code","data_type":"varchar","max_length":20,"is_nullable":false}
	]}`
	mapper := mockParseServer(t, parserResp)

	req := VerifyTableDDLRequest{
		SourceDBType: "mssql", TargetDBType: "postgres",
		SourceTable: &Table{
			Schema:     "dbo",
			Name:       "Companies",
			PrimaryKey: []string{"id"},
			Columns: []Column{
				{Name: "id", DataType: "int", IsNullable: false, IsIdentity: true},
				{Name: "code", DataType: "varchar", MaxLength: 20, IsNullable: false},
			},
		},
		TargetSchema: "public",
		ProposedDDL:  "CREATE TABLE public.companies (id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY, code varchar(20) NOT NULL);",
	}
	verdict, err := mapper.VerifyTableDDL(context.Background(), req)
	if err != nil {
		t.Fatalf("VerifyTableDDL: %v", err)
	}
	if !verdict.OK {
		t.Errorf("expected OK=true, got OK=false with issues: %v", verdict.Issues)
	}
}

// TestVerifyTableDDL_FlagsIssues exercises the parse+compare failure path:
// the AI parses the DDL faithfully (it had halved-varchar values), and Go's
// CompareColumns produces two max_length deltas. The deltas surface as
// Issues in the same shape the legacy prompt produced, so the writer's
// PreviousAttempt feedback is unchanged.
func TestVerifyTableDDL_FlagsIssues(t *testing.T) {
	// Parser faithfully extracts what the (wrong) DDL says — code=10, industry=25.
	parserResp := `{"columns":[
		{"name":"id","data_type":"integer"},
		{"name":"code","data_type":"varchar","max_length":10},
		{"name":"industry","data_type":"varchar","max_length":25}
	]}`
	mapper := mockParseServer(t, parserResp)

	req := VerifyTableDDLRequest{
		SourceDBType: "mssql", TargetDBType: "postgres",
		SourceTable: &Table{
			Schema: "dbo", Name: "Companies", PrimaryKey: []string{"id"},
			Columns: []Column{
				{Name: "id", DataType: "int"},
				// Source had max_length=20 and 50; Go comparison flags both halvings.
				{Name: "code", DataType: "varchar", MaxLength: 20},
				{Name: "industry", DataType: "varchar", MaxLength: 50},
			},
		},
		TargetSchema: "public",
		ProposedDDL:  "CREATE TABLE public.companies (id integer, code varchar(10), industry varchar(25));",
	}
	verdict, err := mapper.VerifyTableDDL(context.Background(), req)
	if err != nil {
		t.Fatalf("VerifyTableDDL: %v", err)
	}
	if verdict.OK {
		t.Errorf("expected OK=false, got OK=true")
	}
	if len(verdict.Issues) != 2 {
		t.Errorf("expected 2 issues, got %d: %v", len(verdict.Issues), verdict.Issues)
	}
	// Sanity-check the issue strings carry the criterion + values — the
	// generator's retry prompt depends on this format being stable.
	for _, issue := range verdict.Issues {
		if !strings.Contains(issue, "max_length") {
			t.Errorf("issue missing criterion: %q", issue)
		}
	}
}

// TestVerifyTableDDL_BadJSONIsRetryable pins the parse-failure handling: a
// model that returns malformed JSON results in verdict.OK=false (so the
// writer retries) rather than a hard error (which would abort the table).
// The error message in Issues feeds back to the next-attempt prompt the
// same way a comparison delta would.
func TestVerifyTableDDL_BadJSONIsRetryable(t *testing.T) {
	mapper := mockParseServer(t, `not even close to JSON`)

	req := VerifyTableDDLRequest{
		SourceDBType: "mssql", TargetDBType: "postgres",
		SourceTable: &Table{
			Schema: "dbo", Name: "Companies",
			Columns: []Column{{Name: "id", DataType: "int"}},
		},
		ProposedDDL: "CREATE TABLE x (id int);",
	}
	verdict, err := mapper.VerifyTableDDL(context.Background(), req)
	if err != nil {
		t.Fatalf("VerifyTableDDL should not return error on bad parse, got: %v", err)
	}
	if verdict.OK {
		t.Error("expected OK=false on parse failure")
	}
	if len(verdict.Issues) != 1 || !strings.Contains(verdict.Issues[0], "could not parse") {
		t.Errorf("expected single issue mentioning parse failure, got %v", verdict.Issues)
	}
}

func TestVerifyTableDDL_RetriesMalformedParserJSONBeforeVerdict(t *testing.T) {
	mapper, calls := mockParseServerSequence(t,
		`{"columns": [{"name": "id", "data_type": "integer"}`,
		`{"columns": [{"name": "id", "data_type": "integer", "is_nullable": false}]}`,
	)

	req := VerifyTableDDLRequest{
		SourceDBType: "mssql", TargetDBType: "postgres",
		SourceTable: &Table{
			Schema: "dbo", Name: "Companies",
			Columns: []Column{{Name: "id", DataType: "int", IsNullable: false}},
		},
		ProposedDDL: "CREATE TABLE x (id integer NOT NULL);",
	}
	verdict, err := mapper.VerifyTableDDL(context.Background(), req)
	if err != nil {
		t.Fatalf("VerifyTableDDL: %v", err)
	}
	if got := calls.Load(); got != 2 {
		t.Fatalf("parser calls = %d, want 2", got)
	}
	if !verdict.OK {
		t.Fatalf("expected retry recovery to produce OK verdict, got issues: %v", verdict.Issues)
	}
}

// TestVerifyTableDDL_RequiresTable + TestVerifyTableDDL_RequiresProposedDDL
// pin the input-validation contract.
func TestVerifyTableDDL_RequiresTable(t *testing.T) {
	mapper := testMapperWithTempCache(t, "anthropic", testProvider("k"))
	_, err := mapper.VerifyTableDDL(context.Background(), VerifyTableDDLRequest{
		ProposedDDL: "CREATE TABLE x (id int);",
	})
	if err == nil {
		t.Error("expected error when SourceTable nil, got nil")
	}
}

func TestVerifyTableDDL_RequiresProposedDDL(t *testing.T) {
	mapper := testMapperWithTempCache(t, "anthropic", testProvider("k"))
	_, err := mapper.VerifyTableDDL(context.Background(), VerifyTableDDLRequest{
		SourceTable: &Table{Name: "x"},
	})
	if err == nil {
		t.Error("expected error when ProposedDDL empty, got nil")
	}
}

func TestVerifyFinalizationDDL_IndexStructuredComparatorOK(t *testing.T) {
	mapper := testMapperWithTempCache(t, "anthropic", testProvider("k"))
	req := VerifyFinalizationDDLRequest{
		Type:         DDLTypeIndex,
		SourceDBType: "mssql", TargetDBType: "postgres",
		Table: &Table{Name: "Companies"},
		Index: &Index{
			Name:        "IX_Companies_Name_Active",
			Columns:     []string{"Name", "IsActive"},
			IsUnique:    true,
			IncludeCols: []string{"CreatedAt"},
			Filter:      "([DeletedAt] IS NULL)",
		},
		ProposedDDL: `CREATE UNIQUE INDEX "ix_companies_name_active" ON "public"."companies" ("name", "isactive") INCLUDE ("createdat") WHERE "deletedat" IS NULL`,
	}
	verdict, err := mapper.VerifyFinalizationDDL(context.Background(), req)
	if err != nil {
		t.Fatalf("VerifyFinalizationDDL index: %v", err)
	}
	if !verdict.OK {
		t.Fatalf("index verifier flagged equivalent DDL: %v", verdict.Issues)
	}
}

func TestVerifyFinalizationDDL_IndexStructuredComparatorMismatch(t *testing.T) {
	mapper := testMapperWithTempCache(t, "anthropic", testProvider("k"))
	req := VerifyFinalizationDDLRequest{
		Type:         DDLTypeIndex,
		SourceDBType: "mssql", TargetDBType: "postgres",
		Table: &Table{Name: "Companies"},
		Index: &Index{
			Name:     "IX_Companies_Name_CreatedAt",
			Columns:  []string{"Name", "CreatedAt"},
			IsUnique: true,
		},
		ProposedDDL: `CREATE UNIQUE INDEX "ix_companies_name_createdat" ON "public"."companies" ("createdat", "name")`,
	}
	verdict, err := mapper.VerifyFinalizationDDL(context.Background(), req)
	if err != nil {
		t.Fatalf("VerifyFinalizationDDL index mismatch: %v", err)
	}
	if verdict.OK {
		t.Fatal("index verifier passed reversed columns")
	}
	if got := strings.Join(verdict.Issues, "\n"); !strings.Contains(got, "columns") {
		t.Fatalf("index mismatch did not report columns: %v", verdict.Issues)
	}
}

func TestVerifyFinalizationDDL_ForeignKeyStructuredComparatorOK(t *testing.T) {
	mapper := testMapperWithTempCache(t, "anthropic", testProvider("k"))
	req := VerifyFinalizationDDLRequest{
		Type:         DDLTypeForeignKey,
		SourceDBType: "mssql", TargetDBType: "postgres",
		Table: &Table{Name: "Orders"},
		ForeignKey: &ForeignKey{
			Name:       "FK_Orders_Customers",
			Columns:    []string{"CustomerID", "TenantID"},
			RefTable:   "Customers",
			RefColumns: []string{"ID", "TenantID"},
			OnDelete:   "CASCADE",
			OnUpdate:   "RESTRICT",
		},
		ProposedDDL: `ALTER TABLE "public"."orders" ADD CONSTRAINT "fk_orders_customers" FOREIGN KEY ("customerid", "tenantid") REFERENCES "public"."customers" ("id", "tenantid") ON DELETE CASCADE`,
	}
	verdict, err := mapper.VerifyFinalizationDDL(context.Background(), req)
	if err != nil {
		t.Fatalf("VerifyFinalizationDDL FK: %v", err)
	}
	if !verdict.OK {
		t.Fatalf("FK verifier flagged equivalent DDL: %v", verdict.Issues)
	}
}

func TestVerifyFinalizationDDL_ForeignKeyStructuredComparatorMismatch(t *testing.T) {
	mapper := testMapperWithTempCache(t, "anthropic", testProvider("k"))
	req := VerifyFinalizationDDLRequest{
		Type:         DDLTypeForeignKey,
		SourceDBType: "mssql", TargetDBType: "postgres",
		Table: &Table{Name: "Orders"},
		ForeignKey: &ForeignKey{
			Name:       "FK_Orders_Customers",
			Columns:    []string{"CustomerID"},
			RefTable:   "Customers",
			RefColumns: []string{"ID"},
			OnDelete:   "CASCADE",
		},
		ProposedDDL: `ALTER TABLE "public"."orders" ADD CONSTRAINT "fk_orders_customers" FOREIGN KEY ("customerid") REFERENCES "public"."customers" ("id")`,
	}
	verdict, err := mapper.VerifyFinalizationDDL(context.Background(), req)
	if err != nil {
		t.Fatalf("VerifyFinalizationDDL FK mismatch: %v", err)
	}
	if verdict.OK {
		t.Fatal("FK verifier passed missing ON DELETE CASCADE")
	}
	if got := strings.Join(verdict.Issues, "\n"); !strings.Contains(got, "on_delete") {
		t.Fatalf("FK mismatch did not report on_delete: %v", verdict.Issues)
	}
}

func TestVerifyFinalizationDDL_CheckStructuredComparatorOK(t *testing.T) {
	mapper := testMapperWithTempCache(t, "anthropic", testProvider("k"))
	req := VerifyFinalizationDDLRequest{
		Type:         DDLTypeCheckConstraint,
		SourceDBType: "mssql", TargetDBType: "postgres",
		Table: &Table{Name: "Companies"},
		CheckConstraint: &CheckConstraint{
			Name:       "CK_Companies_Active",
			Definition: "([IsActive]=(1))",
		},
		ProposedDDL: `ALTER TABLE "public"."companies" ADD CONSTRAINT "ck_companies_active" CHECK ("isactive" = true)`,
	}
	verdict, err := mapper.VerifyFinalizationDDL(context.Background(), req)
	if err != nil {
		t.Fatalf("VerifyFinalizationDDL CHECK: %v", err)
	}
	if !verdict.OK {
		t.Fatalf("CHECK verifier flagged equivalent DDL: %v", verdict.Issues)
	}
}

func TestVerifyFinalizationDDL_CheckStructuredComparatorMismatch(t *testing.T) {
	mapper := testMapperWithTempCache(t, "anthropic", testProvider("k"))
	req := VerifyFinalizationDDLRequest{
		Type:         DDLTypeCheckConstraint,
		SourceDBType: "mssql", TargetDBType: "postgres",
		Table: &Table{Name: "Companies"},
		CheckConstraint: &CheckConstraint{
			Name:       "CK_Companies_Active",
			Definition: "([IsActive]=(1))",
		},
		ProposedDDL: `ALTER TABLE "public"."companies" ADD CONSTRAINT "ck_companies_active" CHECK ("isactive" = false)`,
	}
	verdict, err := mapper.VerifyFinalizationDDL(context.Background(), req)
	if err != nil {
		t.Fatalf("VerifyFinalizationDDL CHECK mismatch: %v", err)
	}
	if verdict.OK {
		t.Fatal("CHECK verifier passed changed predicate")
	}
	if got := strings.Join(verdict.Issues, "\n"); !strings.Contains(got, "predicate") {
		t.Fatalf("CHECK mismatch did not report predicate: %v", verdict.Issues)
	}
}
