package driver

import (
	"context"
	"strings"
	"testing"
)

// TestParseVerifyResponse exercises the OK/ISSUES parser against the
// adversarial inputs we expect from real models — bare OK, OK with trailing
// prose, ISSUES with markdown fences, lowercase, missing header, empty
// response. The parser is fail-closed by contract: anything that doesn't
// clearly say OK is treated as a failure.
func TestParseVerifyResponse(t *testing.T) {
	cases := []struct {
		name      string
		input     string
		wantOK    bool
		wantNonil bool // expect at least one issue when !OK
	}{
		// --- OK paths ---
		{"bare OK", "OK", true, false},
		{"lowercase ok", "ok", true, false},
		{"OK with period", "OK.", true, false},
		{"OK with trailing prose", "OK\n\nNotes: looks fine", true, false},
		{"OK with em-dash and prose", "OK — every column preserves source semantics", true, false},
		{"OK with leading whitespace", "  OK\n", true, false},
		{"OK in markdown fence", "```\nOK\n```", true, false},
		// Unicode-uppercase-byte-length sanity: ß uppercases to SS, expanding
		// the byte length of any prefix containing it. With the previous
		// substring-on-uppercase implementation, the recovered slice index
		// would mis-align. Verify the line-based parser gets it right:
		// "OK" stands alone on the first line, prose follows.
		{"OK with non-ASCII prose", "OK\nWeißbier comment that uppercases to expand bytes", true, false},

		// --- ISSUES paths ---
		{"ISSUES with one line", "ISSUES\ncode: max_length — 20 vs 10", false, true},
		{"ISSUES with multiple lines", "ISSUES\ncode: max_length — 20 vs 10\nname: max_length — 200 vs 100", false, true},
		{"ISSUES with bullet markers", "ISSUES\n- code: max_length — 20 vs 10\n* name: max_length — 200 vs 100", false, true},
		{"ISSUES in markdown fence", "```\nISSUES\ncode: max_length — 20 vs 10\n```", false, true},
		{"lowercase issues", "issues\ncode: max_length — 20 vs 10", false, true},
		{"ISSUES with no body", "ISSUES", false, true},
		{"ISSUES with only blank lines after", "ISSUES\n\n\n", false, true},

		// --- Malformed / fail-closed paths ---
		{"empty response", "", false, true},
		{"only whitespace", "   \n\n  ", false, true},
		{"random prose", "I think this looks fine, but...", false, true},
		{"OKAY (not OK)", "OKAY\nlooks fine", false, true},

		// --- Edge: OK followed by issues should still be OK (the model
		// committed to passing on the first line) — fail-closed parser
		// would re-flag this, but real models that say OK first don't
		// then enumerate issues. Keep first-line semantics.
		{"OK overrides trailing issue-ish text", "OK\nIssues: none worth mentioning", true, false},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			got := parseVerifyResponse(tc.input)
			if got.OK != tc.wantOK {
				t.Errorf("OK = %v, want %v\nresponse:\n%s\nissues: %v", got.OK, tc.wantOK, tc.input, got.Issues)
			}
			if !tc.wantOK && tc.wantNonil && len(got.Issues) == 0 {
				t.Errorf("expected at least one issue for fail case, got none\nresponse:\n%s", tc.input)
			}
		})
	}
}

// TestVerifyTableDDL_OK is the happy path under the parse+compare flow
// (#55): AI parser returns Column[] JSON whose attributes match the source,
// CompareColumns returns zero deltas, verdict.OK=true. No more "auditor says
// OK" — the comparison is mechanical.
func TestVerifyTableDDL_OK(t *testing.T) {
	parserResp := `{"columns":[
		{"name":"id","data_type":"integer","is_nullable":false,"is_identity":true},
		{"name":"code","data_type":"varchar","max_length":20,"is_nullable":false}
	]}`
	mapper := mockParseServer(t, parserResp)

	req := VerifyTableDDLRequest{
		SourceDBType: "mssql", TargetDBType: "postgres",
		SourceTable: &Table{
			Schema:     "dbo",
			Name:       "Companies",
			PrimaryKey: []string{"id"},
			Columns: []Column{
				{Name: "id", DataType: "int", IsNullable: false, IsIdentity: true},
				{Name: "code", DataType: "varchar", MaxLength: 20, IsNullable: false},
			},
		},
		TargetSchema: "public",
		ProposedDDL:  "CREATE TABLE public.companies (id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY, code varchar(20) NOT NULL);",
	}
	verdict, err := mapper.VerifyTableDDL(context.Background(), req)
	if err != nil {
		t.Fatalf("VerifyTableDDL: %v", err)
	}
	if !verdict.OK {
		t.Errorf("expected OK=true, got OK=false with issues: %v", verdict.Issues)
	}
}

// TestVerifyTableDDL_FlagsIssues exercises the parse+compare failure path:
// the AI parses the DDL faithfully (it had halved-varchar values), and Go's
// CompareColumns produces two max_length deltas. The deltas surface as
// Issues in the same shape the legacy prompt produced, so the writer's
// PreviousAttempt feedback is unchanged.
func TestVerifyTableDDL_FlagsIssues(t *testing.T) {
	// Parser faithfully extracts what the (wrong) DDL says — code=10, industry=25.
	parserResp := `{"columns":[
		{"name":"id","data_type":"integer"},
		{"name":"code","data_type":"varchar","max_length":10},
		{"name":"industry","data_type":"varchar","max_length":25}
	]}`
	mapper := mockParseServer(t, parserResp)

	req := VerifyTableDDLRequest{
		SourceDBType: "mssql", TargetDBType: "postgres",
		SourceTable: &Table{
			Schema: "dbo", Name: "Companies", PrimaryKey: []string{"id"},
			Columns: []Column{
				{Name: "id", DataType: "int"},
				// Source had max_length=20 and 50; Go comparison flags both halvings.
				{Name: "code", DataType: "varchar", MaxLength: 20},
				{Name: "industry", DataType: "varchar", MaxLength: 50},
			},
		},
		TargetSchema: "public",
		ProposedDDL:  "CREATE TABLE public.companies (id integer, code varchar(10), industry varchar(25));",
	}
	verdict, err := mapper.VerifyTableDDL(context.Background(), req)
	if err != nil {
		t.Fatalf("VerifyTableDDL: %v", err)
	}
	if verdict.OK {
		t.Errorf("expected OK=false, got OK=true")
	}
	if len(verdict.Issues) != 2 {
		t.Errorf("expected 2 issues, got %d: %v", len(verdict.Issues), verdict.Issues)
	}
	// Sanity-check the issue strings carry the criterion + values — the
	// generator's retry prompt depends on this format being stable.
	for _, issue := range verdict.Issues {
		if !strings.Contains(issue, "max_length") {
			t.Errorf("issue missing criterion: %q", issue)
		}
	}
}

// TestVerifyTableDDL_BadJSONIsRetryable pins the parse-failure handling: a
// model that returns malformed JSON results in verdict.OK=false (so the
// writer retries) rather than a hard error (which would abort the table).
// The error message in Issues feeds back to the next-attempt prompt the
// same way a comparison delta would.
func TestVerifyTableDDL_BadJSONIsRetryable(t *testing.T) {
	mapper := mockParseServer(t, `not even close to JSON`)

	req := VerifyTableDDLRequest{
		SourceDBType: "mssql", TargetDBType: "postgres",
		SourceTable: &Table{
			Schema: "dbo", Name: "Companies",
			Columns: []Column{{Name: "id", DataType: "int"}},
		},
		ProposedDDL: "CREATE TABLE x (id int);",
	}
	verdict, err := mapper.VerifyTableDDL(context.Background(), req)
	if err != nil {
		t.Fatalf("VerifyTableDDL should not return error on bad parse, got: %v", err)
	}
	if verdict.OK {
		t.Error("expected OK=false on parse failure")
	}
	if len(verdict.Issues) != 1 || !strings.Contains(verdict.Issues[0], "could not parse") {
		t.Errorf("expected single issue mentioning parse failure, got %v", verdict.Issues)
	}
}

// TestVerifyTableDDL_RequiresTable + TestVerifyTableDDL_RequiresProposedDDL
// pin the input-validation contract.
func TestVerifyTableDDL_RequiresTable(t *testing.T) {
	mapper := testMapperWithTempCache(t, "anthropic", testProvider("k"))
	_, err := mapper.VerifyTableDDL(context.Background(), VerifyTableDDLRequest{
		ProposedDDL: "CREATE TABLE x (id int);",
	})
	if err == nil {
		t.Error("expected error when SourceTable nil, got nil")
	}
}

func TestVerifyTableDDL_RequiresProposedDDL(t *testing.T) {
	mapper := testMapperWithTempCache(t, "anthropic", testProvider("k"))
	_, err := mapper.VerifyTableDDL(context.Background(), VerifyTableDDLRequest{
		SourceTable: &Table{Name: "x"},
	})
	if err == nil {
		t.Error("expected error when ProposedDDL empty, got nil")
	}
}

// TestBuildVerifyFinalizationDDLPrompt_Index pins the index-audit prompt.
func TestBuildVerifyFinalizationDDLPrompt_Index(t *testing.T) {
	mapper := testMapperWithTempCache(t, "anthropic", testProvider("k"))

	req := VerifyFinalizationDDLRequest{
		Type:         DDLTypeIndex,
		SourceDBType: "mssql", TargetDBType: "postgres",
		Table:        &Table{Name: "orders"},
		TargetSchema: "public",
		Index: &Index{
			Name: "idx_customer", Columns: []string{"customer_id"},
			IsUnique: true, Filter: "deleted_at IS NULL",
		},
		ProposedDDL: "CREATE UNIQUE INDEX idx_customer ON public.orders (customer_id) WHERE deleted_at IS NULL;",
	}
	prompt := mapper.buildVerifyIndexDDLPrompt(req)

	for _, needle := range []string{
		"AUDIT CRITERIA",
		"exact column list",
		"UNIQUE-ness",
		"INCLUDE columns",
		"Filter / WHERE clause",
		"OUTPUT FORMAT",
		"OK",
		"ISSUES",
	} {
		if !strings.Contains(prompt, needle) {
			t.Errorf("verify index prompt missing required phrase %q", needle)
		}
	}
}

// TestBuildVerifyFinalizationDDLPrompt_FK pins the FK-audit prompt.
func TestBuildVerifyFinalizationDDLPrompt_FK(t *testing.T) {
	mapper := testMapperWithTempCache(t, "anthropic", testProvider("k"))

	req := VerifyFinalizationDDLRequest{
		Type:         DDLTypeForeignKey,
		SourceDBType: "mssql", TargetDBType: "postgres",
		Table:        &Table{Name: "orders"},
		TargetSchema: "public",
		ForeignKey: &ForeignKey{
			Name: "fk_customer", Columns: []string{"customer_id"},
			RefSchema: "public", RefTable: "customers", RefColumns: []string{"id"},
			OnDelete: "CASCADE", OnUpdate: "NO ACTION",
		},
		ProposedDDL: "ALTER TABLE public.orders ADD CONSTRAINT fk_customer FOREIGN KEY (customer_id) REFERENCES public.customers (id) ON DELETE CASCADE;",
	}
	prompt := mapper.buildVerifyForeignKeyDDLPrompt(req)

	for _, needle := range []string{
		"AUDIT CRITERIA",
		"local column list",
		"referenced column list",
		"referenced table name",
		"ON DELETE action",
		"ON UPDATE action",
		"NO ACTION and RESTRICT as equivalent",
		"OUTPUT FORMAT",
	} {
		if !strings.Contains(prompt, needle) {
			t.Errorf("verify FK prompt missing required phrase %q", needle)
		}
	}
}

// TestBuildVerifyFinalizationDDLPrompt_Check pins the CHECK-audit prompt.
func TestBuildVerifyFinalizationDDLPrompt_Check(t *testing.T) {
	mapper := testMapperWithTempCache(t, "anthropic", testProvider("k"))

	req := VerifyFinalizationDDLRequest{
		Type:         DDLTypeCheckConstraint,
		SourceDBType: "mssql", TargetDBType: "postgres",
		Table:        &Table{Name: "orders"},
		TargetSchema: "public",
		CheckConstraint: &CheckConstraint{
			Name:       "chk_total_positive",
			Definition: "total >= 0",
		},
		ProposedDDL: "ALTER TABLE public.orders ADD CONSTRAINT chk_total_positive CHECK (total >= 0);",
	}
	prompt := mapper.buildVerifyCheckConstraintDDLPrompt(req)

	for _, needle := range []string{
		"AUDIT CRITERIA",
		"semantics of the source predicate",
		"ISNULL(a,b)",
		"COALESCE(a,b)",
		"constraint name",
		"OUTPUT FORMAT",
	} {
		if !strings.Contains(prompt, needle) {
			t.Errorf("verify CHECK prompt missing required phrase %q", needle)
		}
	}
}
