package driver

import (
	"context"
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"smt/internal/secrets"
)

type liveAISmokeReport struct {
	Provider          string `json:"provider"`
	Model             string `json:"model"`
	CallAIJSON        bool   `json:"call_ai_json"`
	DDLParseColumns   int    `json:"ddl_parse_columns"`
	DiagnosisCategory string `json:"diagnosis_category"`
	FixConfidence     string `json:"fix_confidence"`
	PassedAt          string `json:"passed_at"`
}

func TestLiveAIReviewAndAdvisorySmoke(t *testing.T) {
	if os.Getenv(secrets.LiveAIEnvVar) != "1" {
		t.Skip("set SMT_LIVE_AI=1 to load configured AI secrets and call a live provider")
	}
	if testing.Short() {
		t.Skip("skipping live AI smoke under -short")
	}
	secrets.Reset()
	t.Cleanup(secrets.Reset)

	mapper, err := NewAITypeMapperFromSecrets()
	if err != nil {
		t.Fatalf("loading live AI provider from secrets: %v", err)
	}

	timeout := time.Duration(mapper.TimeoutSeconds()+30) * time.Second
	ctx, cancel := context.WithTimeout(context.Background(), timeout)
	defer cancel()

	response, err := mapper.CallAI(ctx, liveAIJSONPrompt())
	if err != nil {
		t.Fatalf("CallAI live JSON probe failed: %v", err)
	}
	var probe struct {
		OK bool `json:"ok"`
	}
	if err := json.Unmarshal([]byte(extractLiveAIJSONObject(response)), &probe); err != nil {
		t.Fatalf("CallAI response was not parseable JSON: %v", err)
	}
	if !probe.OK {
		t.Fatalf("CallAI JSON probe returned ok=false: %s", truncateString(response, 120))
	}

	columns, err := mapper.parseTargetDDLToColumns(ctx, `CREATE TABLE public.live_ai_smoke (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT NOT NULL DEFAULT 'unknown',
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
)`, "postgres")
	if err != nil {
		t.Fatalf("live AI DDL parse smoke failed: %v", err)
	}
	if len(columns) != 3 {
		t.Fatalf("live AI DDL parse columns=%d, want 3", len(columns))
	}

	diagnoser := NewAIErrorDiagnoser(mapper)
	diagnosis, err := diagnoser.Diagnose(ctx, &ErrorContext{
		ErrorMessage: "rendering CREATE TABLE DDL for dbo.Subscriptions: unsupported SQL expression function \"CONVERT\" in default CONVERT(date, GETDATE())",
		TableName:    "Subscriptions",
		TableSchema:  "dbo",
		Columns: []Column{{
			Name:              "StartsOn",
			DataType:          "date",
			IsNullable:        false,
			DefaultExpression: "CONVERT(date, GETDATE())",
		}},
		SourceDBType: "mssql",
		TargetDBType: "postgres",
		TargetMode:   "schema",
	})
	if err != nil {
		t.Fatalf("live AI diagnosis smoke failed: %v", err)
	}
	if diagnosis.Cause == "" || len(diagnosis.Suggestions) == 0 || diagnosis.Confidence == "" || diagnosis.Category == "" {
		t.Fatalf("diagnosis missing structured fields: %#v", diagnosis)
	}

	fix, err := diagnoser.SuggestExpressionFix(ctx, FixRequest{
		Kind:          "default",
		SourceExpr:    "GETUTCDATE()",
		ColumnName:    "CreatedAt",
		ColumnType:    "datetime2",
		SourceDialect: "mssql",
		TargetDialect: "postgres",
	})
	if err != nil {
		t.Fatalf("live AI expression-fix smoke failed: %v", err)
	}
	if err := ValidateTargetExpression(fix.Expression); err != nil {
		t.Fatalf("live AI expression fix did not pass structural validation: %v (expression %q)", err, fix.Expression)
	}

	writeLiveAIReport(t, liveAISmokeReport{
		Provider:          mapper.ProviderName(),
		Model:             mapper.Model(),
		CallAIJSON:        true,
		DDLParseColumns:   len(columns),
		DiagnosisCategory: diagnosis.Category,
		FixConfidence:     fix.Confidence,
		PassedAt:          time.Now().UTC().Format(time.RFC3339),
	})
}

func liveAIJSONPrompt() string {
	// Keep this above the AI client's short-prompt threshold so it is handled
	// as a general JSON response, not as a type-mapping prompt.
	return `Return ONLY this JSON object, with no markdown and no surrounding prose:
{"ok": true}

This is an SMT release smoke test for the configured AI provider. The response
must be machine-parseable JSON and must not include secrets, API keys, code
blocks, or explanatory text. Repeat the exact requested JSON object only.
` + strings.Repeat("JSON only. ", 60)
}

func extractLiveAIJSONObject(response string) string {
	cleaned := strings.TrimSpace(stripMarkdownFence(response))
	start := strings.Index(cleaned, "{")
	end := strings.LastIndex(cleaned, "}")
	if start >= 0 && end > start {
		return cleaned[start : end+1]
	}
	return cleaned
}

func writeLiveAIReport(t *testing.T, report liveAISmokeReport) {
	t.Helper()
	reportDir := os.Getenv("SMT_LIVE_AI_REPORT_DIR")
	if reportDir == "" {
		return
	}
	if err := os.MkdirAll(reportDir, 0700); err != nil {
		t.Fatalf("creating live AI report dir: %v", err)
	}
	blob, err := json.MarshalIndent(report, "", "  ")
	if err != nil {
		t.Fatalf("marshaling live AI report: %v", err)
	}
	path := filepath.Join(reportDir, "live_ai_smoke.json")
	if err := os.WriteFile(path, blob, 0600); err != nil {
		t.Fatalf("writing live AI report: %v", err)
	}
	t.Logf("live AI smoke report written to %s", path)
}
