package driver

import (
	"context"
	"encoding/json"
	"io"
	"net/http"
	"net/http/httptest"
	"strings"
	"sync/atomic"
	"testing"

	"smt/internal/secrets"
)

// TestParseTargetDDLToColumns_HappyPath asserts the parser threads a clean
// JSON response through CallAI → parsedTargetDDL → []Column without
// modification. This is the load-bearing case — the AI returns exactly what
// the schema asks for and the comparator gets a faithful Column[].
func TestParseTargetDDLToColumns_HappyPath(t *testing.T) {
	resp := `{
		"columns": [
			{"name": "id", "data_type": "integer", "max_length": 0, "precision": 0, "scale": 0, "is_nullable": false, "is_identity": true, "default_expression": "", "is_computed": false, "computed_expression": "", "computed_persisted": false},
			{"name": "code", "data_type": "varchar", "max_length": 20, "precision": 0, "scale": 0, "is_nullable": false, "is_identity": false, "default_expression": "", "is_computed": false, "computed_expression": "", "computed_persisted": false},
			{"name": "created_at", "data_type": "timestamp", "max_length": 0, "precision": 0, "scale": 0, "is_nullable": false, "is_identity": false, "default_expression": "CURRENT_TIMESTAMP", "is_computed": false, "computed_expression": "", "computed_persisted": false}
		]
	}`
	mapper := mockParseServer(t, resp)
	cols, err := mapper.parseTargetDDLToColumns(context.Background(),
		"CREATE TABLE x (id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY, code varchar(20) NOT NULL, created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP);",
		"postgres")
	if err != nil {
		t.Fatalf("parseTargetDDLToColumns: %v", err)
	}
	if len(cols) != 3 {
		t.Fatalf("expected 3 columns, got %d", len(cols))
	}
	// Spot-check key fields the comparator relies on:
	if cols[0].Name != "id" || !cols[0].IsIdentity {
		t.Errorf("col[0] = %+v, expected id with IsIdentity=true", cols[0])
	}
	if cols[1].MaxLength != 20 {
		t.Errorf("col[1].MaxLength = %d, want 20", cols[1].MaxLength)
	}
	if cols[2].DefaultExpression != "CURRENT_TIMESTAMP" {
		t.Errorf("col[2].DefaultExpression = %q, want CURRENT_TIMESTAMP", cols[2].DefaultExpression)
	}
}

// TestParseTargetDDLToColumns_StripsMarkdownFence covers the very common
// "model wrapped JSON in ```" failure mode — without the fence stripper, JSON
// decode fails on the leading backticks. The fence stripper is shared with
// the other AI paths so we exercise it through the parser entrypoint.
func TestParseTargetDDLToColumns_StripsMarkdownFence(t *testing.T) {
	resp := "```json\n{\"columns\":[{\"name\":\"id\",\"data_type\":\"integer\",\"is_nullable\":false}]}\n```"
	mapper := mockParseServer(t, resp)
	cols, err := mapper.parseTargetDDLToColumns(context.Background(), "CREATE TABLE x (id int);", "postgres")
	if err != nil {
		t.Fatalf("parseTargetDDLToColumns: %v", err)
	}
	if len(cols) != 1 || cols[0].Name != "id" {
		t.Errorf("expected single column 'id', got %+v", cols)
	}
}

// TestParseTargetDDLToColumns_TolerateProseWrapping covers a less-clean
// failure mode: model wrote a leading sentence before the JSON, or a
// trailing apology. Pulling out everything between the first `{` and the
// last `}` recovers the JSON.
func TestParseTargetDDLToColumns_TolerateProseWrapping(t *testing.T) {
	resp := "Here is the parsed DDL:\n{\"columns\":[{\"name\":\"id\",\"data_type\":\"integer\"}]}\nLet me know if anything looks off."
	mapper := mockParseServer(t, resp)
	cols, err := mapper.parseTargetDDLToColumns(context.Background(), "CREATE TABLE x (id int);", "postgres")
	if err != nil {
		t.Fatalf("parseTargetDDLToColumns: %v", err)
	}
	if len(cols) != 1 {
		t.Errorf("expected 1 column, got %d", len(cols))
	}
}

// TestParseTargetDDLToColumns_MalformedJSON returns a clear error so the
// writer's retry loop can feed it back to the generator. The loop will
// re-prompt with the parse error in PreviousAttempt.Error — a bad-JSON
// response is a retryable signal exactly like a bad-DDL response.
func TestParseTargetDDLToColumns_MalformedJSON(t *testing.T) {
	resp := `{"columns": [{"name": "id", "data_type": "integer"}` // missing close brackets
	mapper := mockParseServer(t, resp)
	_, err := mapper.parseTargetDDLToColumns(context.Background(), "CREATE TABLE x (id int);", "postgres")
	if err == nil {
		t.Fatal("expected error on malformed JSON, got nil")
	}
	if !strings.Contains(err.Error(), "JSON decode") {
		t.Errorf("expected error to mention JSON decode, got %v", err)
	}
}

func TestParseTargetDDLToColumns_RetriesMalformedJSON(t *testing.T) {
	mapper, calls := mockParseServerSequence(t,
		`{"columns": [{"name": "id", "data_type": "integer"}`,
		`{"columns": [{"name": "id", "data_type": "integer", "is_nullable": false}]}`,
	)
	cols, err := mapper.parseTargetDDLToColumns(context.Background(), "CREATE TABLE x (id int NOT NULL);", "postgres")
	if err != nil {
		t.Fatalf("parseTargetDDLToColumns: %v", err)
	}
	if got := calls.Load(); got != 2 {
		t.Fatalf("parser calls = %d, want 2", got)
	}
	if len(cols) != 1 || cols[0].Name != "id" {
		t.Fatalf("expected recovered id column, got %+v", cols)
	}
}

func TestParseTargetDDLToColumns_RetriesAnthropicMaxTokensStop(t *testing.T) {
	provider := testProvider("test-key")
	provider.Model = "claude-sonnet-5"
	mapper := testMapperWithTempCache(t, "anthropic", provider)
	calls := &atomic.Int32{}
	mapper.client = &http.Client{Transport: roundTripFunc(func(r *http.Request) (*http.Response, error) {
		idx := calls.Add(1)
		resp := anthropicResponse{
			Content: []anthropicContentBlock{
				{Type: "text", Text: `{"columns":[`},
			},
			StopReason: "max_tokens",
		}
		if idx > 1 {
			resp = anthropicResponse{
				Content: []anthropicContentBlock{
					{Type: "text", Text: `{"columns": [{"name": "id", "data_type": "integer", "is_nullable": false}]}`},
				},
				StopReason: "end_turn",
			}
		}
		body, err := json.Marshal(resp)
		if err != nil {
			return nil, err
		}
		return &http.Response{
			StatusCode: http.StatusOK,
			Header:     make(http.Header),
			Body:       io.NopCloser(strings.NewReader(string(body))),
		}, nil
	})}

	cols, err := mapper.parseTargetDDLToColumns(context.Background(), "CREATE TABLE x (id int NOT NULL);", "postgres")
	if err != nil {
		t.Fatalf("parseTargetDDLToColumns: %v", err)
	}
	if got := calls.Load(); got != 2 {
		t.Fatalf("parser calls = %d, want 2", got)
	}
	if len(cols) != 1 || cols[0].Name != "id" {
		t.Fatalf("expected recovered id column, got %+v", cols)
	}
}

// TestParseTargetDDLToColumns_EmptyColumns is also a retryable failure —
// either the AI misread the DDL or the DDL is empty. Either way the writer
// should retry.
func TestParseTargetDDLToColumns_EmptyColumns(t *testing.T) {
	resp := `{"columns": []}`
	mapper := mockParseServer(t, resp)
	_, err := mapper.parseTargetDDLToColumns(context.Background(), "CREATE TABLE x (id int);", "postgres")
	if err == nil {
		t.Fatal("expected error on zero columns, got nil")
	}
	if !strings.Contains(err.Error(), "zero columns") {
		t.Errorf("expected error to mention zero columns, got %v", err)
	}
}

// TestParseTargetDDLToColumns_NoJSONObject covers the "model returned only
// prose" pathological case. Same retryable signal class as malformed JSON.
func TestParseTargetDDLToColumns_NoJSONObject(t *testing.T) {
	resp := "I cannot parse this DDL; please clarify."
	mapper := mockParseServer(t, resp)
	_, err := mapper.parseTargetDDLToColumns(context.Background(), "CREATE TABLE x (id int);", "postgres")
	if err == nil {
		t.Fatal("expected error when no JSON object present, got nil")
	}
	if !strings.Contains(err.Error(), "did not contain a JSON object") {
		t.Errorf("expected error to mention JSON object, got %v", err)
	}
}

// TestBuildVerifyParsePrompt_PinsExtractionRules is the regression guard
// for the parse prompt. The model needs unambiguous extraction rules — drop
// any of these phrases and the parser starts emitting wrong shapes (e.g.
// data_type with parens, max_length swapped with precision).
func TestBuildVerifyParsePrompt_PinsExtractionRules(t *testing.T) {
	prompt := buildVerifyParsePrompt("CREATE TABLE x (id integer);", "postgres")

	for _, needle := range []string{
		// Output schema enforcement.
		"OUTPUT SCHEMA",
		"\"columns\":",
		"\"is_identity\":",
		"\"default_expression\":",
		"\"is_computed\":",
		// Extraction rules — each addresses a known parser failure mode.
		"EXTRACTION RULES",
		"data_type carries ONLY the base type name",
		"`VARCHAR(20)` → `varchar`",
		"`NUMERIC(18,4)` → `numeric`",
		"Unbounded text types",
		"max_length=0",
		"is_identity is TRUE for any auto-generated PK default mechanism",
		"GENERATED BY DEFAULT AS IDENTITY",
		"IDENTITY(seed, increment)",
		"AUTO_INCREMENT",
		// Output discipline.
		"OUTPUT CONSTRAINTS",
		"single JSON object starting with `{`",
		"No markdown fences",
		// Wiring.
		"=== TARGET DIALECT ===",
		"postgres",
		"=== TARGET DDL ===",
		"CREATE TABLE x (id integer);",
	} {
		if !strings.Contains(prompt, needle) {
			t.Errorf("parse prompt missing required phrase %q", needle)
		}
	}
}

// mockParseServer wraps a httptest server returning fixed content and binds
// an AITypeMapper to it. Mirrors verifyMockServer in ai_verify_test.go.
func mockParseServer(t *testing.T, content string) *AITypeMapper {
	t.Helper()
	mapper, _ := mockParseServerSequence(t, content)
	return mapper
}

func mockParseServerSequence(t *testing.T, contents ...string) (*AITypeMapper, *atomic.Int32) {
	t.Helper()
	if len(contents) == 0 {
		t.Fatal("mockParseServerSequence requires at least one response")
	}
	calls := &atomic.Int32{}
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		idx := int(calls.Add(1)) - 1
		if idx >= len(contents) {
			idx = len(contents) - 1
		}
		w.WriteHeader(http.StatusOK)
		_ = json.NewEncoder(w).Encode(openAIResponse{
			Choices: []struct {
				Message struct {
					Content          string `json:"content"`
					ReasoningContent string `json:"reasoning_content"`
				} `json:"message"`
				FinishReason string `json:"finish_reason"`
			}{
				{
					Message: struct {
						Content          string `json:"content"`
						ReasoningContent string `json:"reasoning_content"`
					}{Content: contents[idx]},
					FinishReason: "stop",
				},
			},
		})
	}))
	t.Cleanup(server.Close)

	mapper := testMapperWithTempCache(t, "lmstudio", &secrets.Provider{
		APIKey: "", Model: "test-model", BaseURL: server.URL,
	})
	mapper.client = server.Client()
	return mapper, calls
}

type roundTripFunc func(*http.Request) (*http.Response, error)

func (f roundTripFunc) RoundTrip(r *http.Request) (*http.Response, error) {
	return f(r)
}
