package driver

// AI parser for proposed target DDL. The AI's job: take a CREATE TABLE
// statement and return a JSON list of column descriptors matching the
// existing driver.Column shape. The verify pipeline then runs deterministic
// comparison (verify_compare.go) against the source columns. Splits the
// labor along the LLM's strengths — parsing is what they're best at —
// and removes judgment from the model entirely.
//
// See issue #55. Replaces the AI-audits-AI free-text auditor.

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"
)

const verifyParseMaxAttempts = 2

// parsedTargetDDL is the AI-parser response shape. The JSON returned by the
// model is decoded directly into this struct; Columns can then be fed to
// CompareColumns without an intermediate translation.
type parsedTargetDDL struct {
	Columns []Column `json:"columns"`
}

// parseTargetDDLToColumns runs the AI parser on a proposed target DDL and
// returns the parsed []Column. Returns an error if the AI returns malformed
// JSON or empty columns — the writer's retry loop treats this the same as a
// verify-fail (#48 plumbing) and re-asks the generator.
//
// targetDialect is the dialect of the DDL being parsed (postgres / mssql /
// mysql), threaded into the prompt so the parser knows which dialect's
// idioms to expect (e.g. PG `GENERATED BY DEFAULT AS IDENTITY` vs MSSQL
// `IDENTITY(1,1)` vs MySQL `AUTO_INCREMENT`).
func (m *AITypeMapper) parseTargetDDLToColumns(ctx context.Context, ddl string, targetDialect string) ([]Column, error) {
	var lastErr error
	for attempt := 1; attempt <= verifyParseMaxAttempts; attempt++ {
		prompt := buildVerifyParsePrompt(ddl, targetDialect)
		if attempt > 1 {
			prompt = buildVerifyParseRetryPrompt(ddl, targetDialect, lastErr)
		}

		raw, err := m.CallAI(ctx, prompt)
		if err != nil {
			return nil, fmt.Errorf("AI parse call failed: %w", err)
		}

		cols, err := parseTargetDDLResponse(raw)
		if err == nil {
			return cols, nil
		}
		lastErr = err
	}

	return nil, lastErr
}

func parseTargetDDLResponse(raw string) ([]Column, error) {
	cleaned := strings.TrimSpace(stripMarkdownFence(raw))
	if cleaned == "" {
		return nil, fmt.Errorf("AI parser returned empty response")
	}

	// Defend against models that prefix/suffix prose despite instructions.
	// Find the first '{' and the last '}' and parse what's between them.
	start := strings.Index(cleaned, "{")
	end := strings.LastIndex(cleaned, "}")
	if start < 0 || end <= start {
		return nil, fmt.Errorf("AI parser response did not contain a JSON object: %s", truncateString(cleaned, 200))
	}
	jsonBody := cleaned[start : end+1]

	var parsed parsedTargetDDL
	if err := json.Unmarshal([]byte(jsonBody), &parsed); err != nil {
		return nil, fmt.Errorf("AI parser response failed JSON decode: %w (response: %s)",
			err, truncateString(jsonBody, 200))
	}
	if len(parsed.Columns) == 0 {
		return nil, fmt.Errorf("AI parser returned zero columns — DDL may be malformed or parser misread")
	}

	return parsed.Columns, nil
}

func buildVerifyParseRetryPrompt(ddl, targetDialect string, previousErr error) string {
	var sb strings.Builder

	sb.WriteString("You are a SQL DDL parser. Return ONLY valid JSON. Your previous response was invalid or incomplete")
	if previousErr != nil {
		sb.WriteString(": ")
		sb.WriteString(truncateString(previousErr.Error(), 180))
	}
	sb.WriteString(". Re-parse the CREATE TABLE statement and emit one complete JSON object.\n\n")

	sb.WriteString(fmt.Sprintf("=== TARGET DIALECT ===\n%s\n\n", targetDialect))
	sb.WriteString("=== TARGET DDL ===\n")
	sb.WriteString(ddl)
	sb.WriteString("\n\n")

	sb.WriteString("=== OUTPUT SCHEMA ===\n")
	sb.WriteString(`{"columns":[{"name":"","data_type":"","max_length":0,"precision":0,"scale":0,"datetime_precision":0,"is_unsigned":false,"display_width":0,"is_nullable":false,"is_identity":false,"default_expression":"","is_computed":false,"computed_expression":"","computed_persisted":false,"enum_values":[]}]}`)
	sb.WriteString("\n\n")

	sb.WriteString("Rules: emit one columns[] entry per DDL column in order; strip type modifiers into numeric fields; use zero values instead of null; preserve default/computed text; use dialect defaults for temporal precision; output must start with { and end with }.")

	return sb.String()
}

// buildVerifyParsePrompt composes the prompt that turns a proposed target
// DDL into structured Column[] JSON. Deliberately small — parsing is the
// LLM's strength, so the prompt mostly defines the output schema and a few
// dialect-aware extraction rules. No comparison logic, no judgment, no
// equivalence lists. Compare to the ~400-line audit prompt this replaces.
func buildVerifyParsePrompt(ddl, targetDialect string) string {
	var sb strings.Builder

	sb.WriteString("You are a SQL DDL parser. Parse the CREATE TABLE statement below into a JSON object describing each column. Output only the JSON — no prose, no markdown fences.\n\n")

	sb.WriteString(fmt.Sprintf("=== TARGET DIALECT ===\n%s\n\n", targetDialect))
	sb.WriteString("=== TARGET DDL ===\n")
	sb.WriteString(ddl)
	sb.WriteString("\n\n")

	sb.WriteString("=== OUTPUT SCHEMA ===\n")
	sb.WriteString("Emit a single JSON object with this exact shape:\n")
	sb.WriteString(`{
  "columns": [
    {
      "name": "<exact column name as written in the DDL>",
      "data_type": "<base type name, lowercase, NO length or precision modifiers>",
      "max_length": <integer; characters for char/varchar/nvarchar/text-class types; 0 if not applicable or unbounded>,
      "precision": <integer; for decimal/numeric/money — total digits; 0 otherwise>,
      "scale": <integer; for decimal/numeric/money — fractional digits; 0 otherwise>,
      "datetime_precision": <integer; fractional-seconds digits for date/time/timestamp types — the explicit N in TIMESTAMP(N)/DATETIME2(N)/DATETIMEOFFSET(N)/TIME(N), else the dialect default per rule 9 (0 for MySQL, 6 for PostgreSQL, 7 for SQL Server); 0 when not a temporal type>,
      "is_unsigned": <true for an UNSIGNED numeric type (MySQL); false otherwise>,
      "display_width": <integer; the N in MySQL tinyint(N) — e.g. TINYINT(1) → 1; 0 for every other type>,
      "is_nullable": <true if the column allows NULL, false if NOT NULL or PRIMARY KEY>,
      "is_identity": <true if the column auto-increments; see EXTRACTION RULES below>,
      "default_expression": "<exact default clause text, or empty string>",
      "is_computed": <true for generated/computed columns>,
      "computed_expression": "<the generation expression, or empty>",
      "computed_persisted": <true for STORED/PERSISTED computed columns>,
      "enum_values": [<for MySQL ENUM/SET: member string values in declaration order; [] otherwise>]
    }
  ]
}
`)
	sb.WriteString("\n=== EXTRACTION RULES ===\n")
	sb.WriteString("1. data_type carries ONLY the base type name (lowercase). Strip parens and parameters: `VARCHAR(20)` → `varchar` with max_length=20; `NUMERIC(18,4)` → `numeric` with precision=18, scale=4. The stripped modifiers go in their dedicated fields — fractional-seconds precision in datetime_precision, the tinyint width in display_width, UNSIGNED in is_unsigned, enum/set members in enum_values (rules 9-12).\n")
	sb.WriteString("2. Unbounded text types (`TEXT`, `NTEXT`, `CLOB`, `MEDIUMTEXT`, `LONGTEXT`, `VARCHAR(MAX)`, `NVARCHAR(MAX)`) → max_length=0.\n")
	sb.WriteString("3. Integer types (`INT`, `BIGINT`, `SMALLINT`) → max_length=0, precision=0, scale=0 (the dialect's default precision is irrelevant for verification).\n")
	sb.WriteString("4. is_identity is TRUE for any auto-generated PK default mechanism:\n")
	sb.WriteString("   - PostgreSQL: `GENERATED BY DEFAULT AS IDENTITY`, `GENERATED ALWAYS AS IDENTITY`, or `DEFAULT nextval('seq')`.\n")
	sb.WriteString("   - SQL Server: `IDENTITY(seed, increment)`.\n")
	sb.WriteString("   - MySQL/MariaDB: `AUTO_INCREMENT`.\n")
	sb.WriteString("   When is_identity=true, leave default_expression empty (the identity mechanism IS the default).\n")
	sb.WriteString("5. default_expression captures the literal text after `DEFAULT`, including any wrapping parentheses (e.g. `((0))`, `(getutcdate())`, `'pending'`, `CURRENT_TIMESTAMP`). Empty string when no DEFAULT clause is present (and not an identity column).\n")
	sb.WriteString("6. Computed columns (`GENERATED ALWAYS AS (expr) STORED|VIRTUAL`, MSSQL `AS (expr) PERSISTED`) → is_computed=true, computed_expression=<expr>, computed_persisted=true for STORED/PERSISTED, false for VIRTUAL or unspecified.\n")
	sb.WriteString("7. is_nullable: false for `NOT NULL`, false for PRIMARY KEY columns, true otherwise.\n")
	sb.WriteString("8. Names: preserve exact case as written in the DDL. Strip surrounding quoting characters (`\"`, `[]`, backticks).\n")
	sb.WriteString("9. datetime_precision: the fractional-seconds precision of a temporal type — the N in `TIMESTAMP(N)`, `DATETIME2(N)`, `DATETIMEOFFSET(N)`, `TIME(N)`, `timestamp(N) with|without time zone`. When a temporal type is written WITHOUT an explicit precision, use the dialect's stored default, NOT 0: PostgreSQL `timestamp`/`timestamptz`/`time` = 6; SQL Server `datetime2`/`datetimeoffset`/`time` = 7; MySQL `TIMESTAMP`/`DATETIME`/`TIME` = 0. Use 0 for non-temporal types. This is SEPARATE from precision/scale, which are for decimal/numeric/money only.\n")
	sb.WriteString("10. is_unsigned: true for a MySQL `... UNSIGNED` numeric type (`INT UNSIGNED`, `BIGINT UNSIGNED`, `TINYINT UNSIGNED`, ...); false otherwise.\n")
	sb.WriteString("11. display_width: the integer N in MySQL `tinyint(N)` (e.g. `TINYINT(1)` → 1). Capture it ONLY for tinyint; 0 for every other type.\n")
	sb.WriteString("12. enum_values: for MySQL `ENUM(...)` / `SET(...)`, the list of member string values in declaration order (`ENUM('a','b')` → [\"a\",\"b\"]); empty array for non-enum/set types.\n\n")

	sb.WriteString("=== OUTPUT CONSTRAINTS ===\n")
	sb.WriteString("- Output MUST be a single JSON object starting with `{` and ending with `}`.\n")
	sb.WriteString("- No markdown fences. No prose before or after the JSON. No comments inside the JSON.\n")
	sb.WriteString("- One columns[] entry per column in the DDL, in declaration order.\n")
	sb.WriteString("- If a field's value is unknown or not applicable, use the type's zero value (0 for ints, false for bools, \"\" for strings, [] for arrays) — never null.\n")

	return sb.String()
}
