"""Alembic migration management — programmatic wrapper."""

from __future__ import annotations

import configparser
import datetime
import logging
import re
from io import StringIO
from pathlib import Path

from alembic import command
from alembic.config import Config
from alembic.script import ScriptDirectory

logger = logging.getLogger(__name__)

# Alembic operation patterns used to detect non-empty migrations
_OP_PATTERNS = re.compile(
    r"op\.(create_table|drop_table|add_column|drop_column|"
    r"create_index|drop_index|alter_column|create_unique_constraint|"
    r"drop_constraint|create_foreign_key|create_check_constraint)"
)

# Collation patterns to strip from generated migrations
_COLLATION_PATTERNS = [
    (re.compile(r",\s*collation='[^']*'"), ""),
    (re.compile(r"collation='[^']*',\s*"), ""),
    (re.compile(r"\(collation='[^']*'\)"), "()"),
]

# Template for env.py
_ENV_PY_TEMPLATE = Path(__file__).parent / "templates" / "env.py.mako"


class MigrationError(Exception):
    """Raised when a migration operation fails."""


class MigrationManager:
    """Wraps Alembic operations for programmatic use."""

    def __init__(self, workspace: Path, target_url: str, target_schema: str):
        self.workspace = Path(workspace)
        self.target_url = target_url
        self.target_schema = target_schema
        self.alembic_dir = self.workspace / "alembic"
        self.versions_dir = self.alembic_dir / "versions"
        self.ini_path = self.workspace / "alembic.ini"

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def init_alembic(self) -> None:
        """Initialize Alembic configuration and directory structure."""
        self.workspace.mkdir(parents=True, exist_ok=True)

        config = self._get_config()

        if not self.alembic_dir.exists():
            logger.info("Initializing Alembic...")
            command.init(config, str(self.alembic_dir))
        else:
            logger.info("Alembic already initialized, updating configuration...")

        self._write_env_py()
        self._update_ini_url()
        logger.info("Alembic configuration ready")

    def create_migration(self, message: str = "Schema migration") -> Path | None:
        """Create an autogenerated migration.

        Returns the migration file path, or None if no changes detected.
        """
        config = self._get_config()

        # Apply pending migrations first if not at head
        current = self.get_current_revision()
        head = self.get_head_revision()
        if current != head and head is not None:
            logger.info("Applying pending migrations before creating new one...")
            command.upgrade(config, "head")

        # Generate migration
        logger.info("Checking for schema differences...")
        command.revision(config, autogenerate=True, message=message)

        # Find the newest migration file
        migration_file = self._find_latest_migration()
        if migration_file is None:
            logger.info("No migration file generated")
            return None

        # Check if migration is empty
        if self._is_migration_empty(migration_file):
            logger.info("No schema changes detected — removing empty migration")
            migration_file.unlink()
            return None

        # Strip collations
        stripped = self._strip_collations(migration_file)
        if stripped > 0:
            logger.warning("Stripped %d collation reference(s) from migration", stripped)

        # Summary
        ops = self._count_operations(migration_file)
        logger.info(
            "Migration created: %s (%d table(s), %d column(s), %d index(es))",
            migration_file.name,
            ops.get("create_table", 0),
            ops.get("add_column", 0),
            ops.get("create_index", 0),
        )

        return migration_file

    def apply_migration(self, dry_run: bool = False) -> Path | None:
        """Apply pending migrations.

        Args:
            dry_run: If True, generate DDL SQL file but don't execute.

        Returns path to the DDL SQL file, or None if already at head.
        """
        current = self.get_current_revision()
        head = self.get_head_revision()

        if current == head and head is not None:
            logger.info("Already at head — no migrations to apply")
            return None

        if head is None:
            logger.info("No migration files found")
            return None

        # Generate DDL SQL file
        ddl_path = self._generate_ddl_file()
        logger.info("DDL SQL saved to: %s", ddl_path)

        if dry_run:
            logger.info("Dry run — migration not applied. Review DDL at: %s", ddl_path)
            return ddl_path

        # Apply
        config = self._get_config()
        logger.info("Applying migration...")
        command.upgrade(config, "head")

        new_rev = self.get_current_revision()
        logger.info("Migration applied. Current revision: %s", new_rev)

        return ddl_path

    def rollback(self, target: str = "base") -> None:
        """Rollback migrations.

        Args:
            target: 'base', '-1', '-N', or a specific revision hash.
        """
        current = self.get_current_revision()
        if current is None:
            logger.info("No migrations applied — nothing to rollback")
            return

        config = self._get_config()
        logger.info("Rolling back to '%s'...", target)
        command.downgrade(config, target)

        new_rev = self.get_current_revision()
        if new_rev:
            logger.info("Rolled back to revision: %s", new_rev)
        else:
            logger.info("Rolled back to base (no migrations applied)")

    def get_current_revision(self) -> str | None:
        """Get the current applied revision hash."""
        if not self.ini_path.exists():
            return None

        from alembic.runtime.migration import MigrationContext
        from sqlalchemy import create_engine

        engine = create_engine(self.target_url)
        try:
            with engine.connect() as conn:
                ctx = MigrationContext.configure(conn)
                heads = ctx.get_current_heads()
                return heads[0] if heads else None
        finally:
            engine.dispose()

    def get_head_revision(self) -> str | None:
        """Get the latest available revision from migration files."""
        if not self.ini_path.exists():
            return None
        config = self._get_config()
        script = ScriptDirectory.from_config(config)
        heads = script.get_heads()
        return heads[0] if heads else None

    def get_history(self) -> list[str]:
        """Get migration history as list of revision descriptions."""
        if not self.ini_path.exists():
            return []
        config = self._get_config()
        output = StringIO()
        config.output_buffer = output
        command.history(config, verbose=True)
        return output.getvalue().strip().split("\n") if output.getvalue().strip() else []

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _get_config(self) -> Config:
        """Create an Alembic Config pointing at the workspace."""
        config = Config(str(self.ini_path))
        config.set_main_option("script_location", str(self.alembic_dir))
        return config

    def _write_env_py(self) -> None:
        """Write the env.py file from the template."""
        env_path = self.alembic_dir / "env.py"
        template_content = _ENV_PY_TEMPLATE.read_text()
        env_path.write_text(template_content)
        logger.debug("Wrote env.py to %s", env_path)

    def _update_ini_url(self) -> None:
        """Update alembic.ini with the target database URL."""
        if not self.ini_path.exists():
            return

        config = configparser.ConfigParser()
        config.read(str(self.ini_path))

        # Escape % as %% for INI format
        url_escaped = self.target_url.replace("%", "%%")
        config.set("alembic", "sqlalchemy.url", url_escaped)

        with open(self.ini_path, "w") as f:
            config.write(f)

        logger.debug("Updated alembic.ini with target URL")

    def _find_latest_migration(self) -> Path | None:
        """Find the most recently created migration file."""
        if not self.versions_dir.exists():
            return None

        py_files = sorted(
            self.versions_dir.glob("*.py"),
            key=lambda p: p.stat().st_mtime,
            reverse=True,
        )
        return py_files[0] if py_files else None

    def _is_migration_empty(self, filepath: Path) -> bool:
        """Check if a migration file contains actual operations."""
        content = filepath.read_text()
        return _OP_PATTERNS.search(content) is None

    def _strip_collations(self, filepath: Path) -> int:
        """Remove collation= parameters from migration file.

        Returns count of collation references removed.
        """
        content = filepath.read_text()
        count = len(re.findall(r"collation='[^']*'", content))

        if count == 0:
            return 0

        for pattern, replacement in _COLLATION_PATTERNS:
            content = pattern.sub(replacement, content)

        filepath.write_text(content)

        remaining = len(re.findall(r"collation='[^']*'", content))
        if remaining > 0:
            logger.warning("%d collation reference(s) could not be removed", remaining)

        return count - remaining

    def _count_operations(self, filepath: Path) -> dict[str, int]:
        """Count migration operations by type."""
        content = filepath.read_text()
        counts: dict[str, int] = {}
        for match in _OP_PATTERNS.finditer(content):
            op = match.group(1)
            counts[op] = counts.get(op, 0) + 1
        return counts

    def _generate_ddl_file(self) -> Path:
        """Generate DDL SQL file using Alembic offline mode."""
        timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
        ddl_path = self.workspace / f"migration_{timestamp}.sql"

        config = self._get_config()
        output = StringIO()
        config.output_buffer = output
        command.upgrade(config, "head", sql=True)

        ddl_path.write_text(output.getvalue())
        return ddl_path
